test:
  image: ubuntu:xenial
  script:
    - apt-get update -qq && apt-get install -y
        postgresql-11
		postgresql-11-postgis-2.5
		postgresql-11-postgis-2.5-scripts
		postgis
    - RUNTESTFLAGS=-v make check
