sudo: required
dist: trusty

language: sql

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
    - postgresql-9.6-postgis-2.3-scripts

script:
  - echo "select version()" | psql template1
  - make check RUNTESTFLAGS=-v
