sudo: required
dist: trusty

language: sql

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgis

script:
  - echo "select version()" | psql template1
  - echo "select PostGIS_Full_Version()" | psql template1
  - make check RUNTESTFLAGS=-v
