addons: 
  postgresql: "9.5"
before_script: 
  - "psql -U postgres -a -c \"create extension postgis;\""
dist: trusty
language: ruby
script: 
  - "echo \"select version()\" | psql template1"
  - "echo \"select postgis_full_version()\" | psql template1"
  - "make check RUNTESTFLAGS=-v"
sudo: required
