sudo: false

language: sql

addons:
  postgresql: "9.3"
  apt:
    packages:
    - postgis
    - postgresql-9.3-postgis-2.1
    - postgresql-9.3-postgis-scripts

script:
  - echo "select version()" | psql template1
  - make check RUNTESTFLAGS=-v
