sudo: required
dist: trusty

language: sql

addons:
  postgresql: "9.5"
  apt:
    packages:
    - postgis

before_script:
 - psql -U postgres -c "create extension postgis"
 
script:
  - echo "select version()" | psql template1
  - echo "select postgis_full_version()" | psql template1
  - make check RUNTESTFLAGS=-v
 
