sudo: required
dist: trusty

language: sql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgis

global:
    - PGPORT=5432

script:
  - echo "select version()" | psql template1
  - make check RUNTESTFLAGS=-v
