sudo: required
dist: trusty

language: sql

addons:
  postgresql: "9.5"
  apt:
    packages:
    - postgis

script:
  - echo "select PostGIS_Full_Version()" | psql template1
  - make check RUNTESTFLAGS=-v
