sudo: false

language: sql

addons:
  apt:
    packages:
    - postgis
    - postgresql-9.3-postgis-2.1
    - postgresql-9.3-postgis-scripts

script:
  - psql -c 'select version()'
  - make check RUNTESTFLAGS=-v
