sudo: required
dist: trusty

language: sql

addons:
  postgresql: "9.5"
  apt:
    packages:
    - postgis
    - postgresql-9.5-postgis-2.2 
    - postgresql-9.5-postgis-scripts

script:
  - echo "select version()" | psql template1
  - echo "select postgis_full_version()" | psql template1
  - make check RUNTESTFLAGS=-v
 
