sudo: required
dist: trusty

language: sql

before_install:
  - sudo service postgresql stop
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/10/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/10/main
  - sudo service postgresql start 10

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-10-postgis-2.4
    - postgresql-10-postgis-2.4-scripts
    - postgresql-client-10

global:
    - PGPORT=5432

script:
  - echo "select version()" | psql template1
  - make check RUNTESTFLAGS=-v
