addons: 
  postgresql: "9.5"
before_script: 
  - sudo apt-get install -y postgis 
  - sudo apt-get install -y postgresql-contrib-9.5 
  - "psql -U postgres -a -c \"create extension postgis;\""
dist: trusty
language: ruby
script: 
  - "echo \"select version()\" | psql template1"
  - "make check RUNTESTFLAGS=-v"
sudo: required
